export const ReducerType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCT: "SET_PRODUCT",
  SET_MINMAX_PRICE: "SET_MINMAX_PRICE",
  SET_CHECKOUT_DATA: "SET_CHECKOUT_DATA",

  SET_CART: "SET_CART",
  SET_LOGGEDIN: "SET_LOGGEDIN",
  SET_LOGGEDOUT: "SET_LOGGEDOUT",
};

// faffsd
